In [28]:
import torch

%load_ext autoreload
%autoreload 2


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [29]:
torch.cuda.is_available()

True

In [30]:
from logging_ import Logger

In [31]:
l = Logger()

In [32]:
l.load_all()

In [33]:
keys = list(l.dict.keys())

In [34]:
labs = []
for key in keys[1:]:
    labs.append(l.dict[key]["labels_progress"])

In [35]:
labs[0]

array([[7, 5, 7, 8, 8, 8, 6, 1, 8, 8, 9, 8, 7, 0, 3, 1, 2, 4, 9, 7, 1, 1,
        8, 1, 5, 9, 0, 2, 1, 7, 8, 8, 9, 7, 3, 9, 9, 9, 4, 0, 8, 6, 4, 0,
        6, 6, 8, 9, 6, 1, 6, 3, 0, 0, 2, 8, 5, 7, 8, 8, 9, 5, 4, 1, 4, 8,
        5, 5, 2, 6, 0, 5, 3, 6, 5, 3, 6, 3, 6, 5, 2, 7, 9, 6, 8, 1, 5, 0,
        5, 6, 4, 2, 4, 8, 1, 4, 4, 5, 5, 9, 8, 0, 0, 0, 7, 6, 5, 6, 1, 9,
        7, 9, 1, 2, 7, 4, 8, 0, 6, 1, 4, 3, 6, 2, 1, 6, 4, 9, 0, 4, 6, 2,
        3, 2, 1, 4, 9, 4, 4, 1, 9, 6, 7, 6, 4, 3, 4, 6, 3, 5, 7, 9, 4, 1,
        2, 2, 9, 7, 1, 8, 8, 0, 8, 7, 0, 4, 3, 7, 2, 7, 0, 3, 9, 6, 2, 3,
        5, 9, 0, 6, 3, 2, 5, 3, 7, 3, 5, 2, 5, 3, 4, 4, 9, 4, 1, 3, 3, 3,
        0, 9]])

In [36]:
labs[1]

array([[7, 5, 7, 8, 8, 8, 6, 1, 8, 8, 9, 8, 7, 0, 3, 1, 2, 4, 9, 7, 1, 1,
        8, 1, 5, 9, 0, 2, 1, 7, 8, 8, 9, 7, 3, 9, 9, 9, 4, 0, 8, 6, 4, 0,
        6, 6, 8, 9, 6, 1, 6, 3, 0, 0, 2, 8, 5, 7, 8, 8, 9, 5, 4, 1, 4, 8,
        5, 5, 2, 6, 0, 5, 3, 6, 5, 3, 6, 3, 6, 5, 2, 7, 9, 6, 8, 1, 5, 0,
        5, 6, 4, 2, 4, 8, 1, 4, 4, 5, 5, 9, 8, 0, 0, 0, 7, 6, 5, 6, 1, 9,
        7, 9, 1, 2, 7, 4, 8, 0, 6, 1, 4, 3, 6, 2, 1, 6, 4, 9, 0, 4, 6, 2,
        3, 2, 1, 4, 9, 4, 4, 1, 9, 6, 7, 6, 4, 3, 4, 6, 3, 5, 7, 9, 4, 1,
        2, 2, 9, 7, 1, 8, 8, 0, 8, 7, 0, 4, 3, 7, 2, 7, 0, 3, 9, 6, 2, 3,
        5, 9, 0, 6, 3, 2, 5, 3, 7, 3, 5, 2, 5, 3, 4, 4, 9, 4, 1, 3, 3, 3,
        0, 9]])

In [38]:
labs[0] == labs[1]

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
      