In [113]:
from fast_minimum_norm2 import l1_mid_points_, croce_l1_projection, l1_ball_euclidean_projection
from autoattack.autopgd_base import L1_projection
import torch
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [123]:
x0 = torch.tensor([[0.5,1], [.1, .2]])
x1 = torch.tensor([[0.2,-0.4], [1.2, -.3]])
eps = torch.tensor([0.5, 0.5], dtype=torch.float)

In [124]:
l1_mid_points_(x0, x1, eps)

tensor([[0.5000, 0.1500],
        [0.9000, 0.2000]])

In [132]:
x1 - x0 + croce_l1_projection(x0, x1-x0, eps)

tensor([[ 0.0000, -0.5000],
        [ 0.5000,  0.0000]])

In [138]:
x1 -x0 + croce_l1_projection(x0, x1-x0, eps)

tensor([[ 0.0000, -0.5000],
        [ 0.5000,  0.0000]])

In [134]:
l1_ball_euclidean_projection(x1-x0, eps)

tensor([[-0.0000, -0.5000],
        [ 0.5000, -0.0000]])

In [135]:
x0 + l1_ball_euclidean_projection(x1-x0, eps)

tensor([[0.5000, 0.5000],
        [0.6000, 0.2000]])

In [136]:
# L1_projection(x0, x1-x0, eps)